name: Submit a flag
title: 'Submitting a flag'
about: Submit a flag request to the database
labels: ['submit-flag']
assignees: 'jeanpantaleon'
body:
  - type: input
    id: flag_author
    attributes:
      label: 'The author of the flag'
      placeholder: 'Your name'
    validations:
      required: true
  - type: input
    id: flag_name
    attributes:
      label: The name of the flag
      placeholder: Your flag name
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Your image'
